### PR TITLE
Added in VS Marketplace Markdown badges

### PR DESCRIPTION
**Pull request by ohheyrj**
Added in markdown for VS Marketplace:

* Install number
* Version number
* Rating (stars)
* Rating
* Downloads

### CODE REVIEW

**Review by idleberg — CHANGES_REQUESTED** [review]
Please don't commit whitespace changes and respect the original's indentation

**Comment by ohheyrj** [comment]
Hey, made the required changes, apologies for the mistakes.

**Comment by idleberg** [comment]
No worries, thanks a lot for the PR!

**Comment by ohheyrj** [comment]
No problem. If its ok, I will add in any additional ones that I find missing.

**Pull request merged**
